# tos_scan_action_executor.py

from __future__ import annotations

import logging
from pathlib import Path
from typing import Protocol
import time

from scan_action_executor import NoOpScanActionExecutor
from scan_jobs import JobRequest, JobResult, SourceKind
from scan_output import build_output_path


class ToSExportController(Protocol):
    def open_watchlist_export(self) -> None:
        ...

    def normalize_watchlist_export_dialog(self) -> None:
        ...

    def enter_watchlist_filename_then_export_directory(
        self,
        filename: str,
        target_dir: str | Path,
    ) -> None:
        ...

    def confirm_watchlist_save(self) -> None:
        ...

    def export_csv_file(self) -> None:
        ...

    def normalize_scan_export_dialog(self) -> None:
        ...

    def enter_filename(self, filename: str, target_dir: str | Path) -> None:
        ...

    def confirm_save(self) -> None:
        ...


# class WatchlistExportController(Protocol):
#     def open_watchlist_export(self) -> None:
#         ...

#     def normalize_watchlist_export_dialog(self) -> None:
#         ...

#     def enter_watchlist_filename_then_export_directory(
#         self,
#         filename: str,
#         target_dir: str | Path,
#     ) -> None:
#         ...

#     def confirm_watchlist_save(self) -> None:
#         ...


class ToSScanActionExecutor(NoOpScanActionExecutor):
    """
    ToS-backed executor for v2 scan jobs.

    First integration target:
        EXPORT_WL -> real ThinkOrSwim watchlist export

    Other methods intentionally inherit no-op behavior until they are wired
    one at a time.
    """

    def __init__(
        self,
        *,
        action_controller: ToSExportController | None,
        output_dir: Path,
        logger: logging.Logger | None = None,
        dry_run: bool = False,
    ) -> None:
        super().__init__(logger=logger)
        self.action_controller = action_controller
        self.output_dir = Path(output_dir)
        self.dry_run = dry_run

    def _wait_for_output_file(self, output_path: Path, *, timeout_s: float) -> bool:
        deadline = time.monotonic() + timeout_s

        while time.monotonic() < deadline:
            if output_path.exists() and output_path.is_file():
                return True

            time.sleep(0.25)

        return False

    def export_wl(self, request: JobRequest) -> JobResult:
        """
        Export a WL CSV.

        This is intentionally thin. The real ToS details should remain in the
        existing pwidget/action-controller layer.
        """

        output_path = build_output_path(
            output_dir=self.output_dir,
            source=SourceKind.WL,
            when=request.requested_at,
            target_filename=request.target_filename,
        )
        
        if self.dry_run:
            output_path.parent.mkdir(parents=True, exist_ok=True)

            output_path.write_text(
                "Symbol,Source,Note\n"
                "DRYRUN,WL,Generated by ToSScanActionExecutor dry run\n",
                encoding="utf-8",
            )

            message = f"DRY RUN: wrote stub WL CSV to {output_path}"
            self._log_info(message)

            return JobResult(
                request=request,
                ok=True,
                message=message,
                output_path=output_path,
            )

        try:
            # Placeholder call. Replace this with the actual WL export method
            # from your existing ToS action controller.
            #
            # Example possibilities, depending on your existing API:
            #
            #   self.action_controller.export_wl_csv(output_path=output_path)
            #   self.action_controller.export_watchlist_csv(output_path=output_path)
            #   self.action_controller.perform_wl_export(output_path=output_path)
            #
            self._export_wl_with_existing_controller(output_path)
            if not self._wait_for_output_file(output_path, timeout_s=5.0):
                raise RuntimeError(f"WL export file did not appear: {output_path}")

        except Exception as exc:
            message = f"WL export failed: {exc}"
            self._log_error(message)

            return JobResult(
                request=request,
                ok=False,
                message=message,
                output_path=output_path,
                error=str(exc),
            )

        message = f"Exported WL CSV to {output_path}"
        self._log_info(message)

        return JobResult(
            request=request,
            ok=True,
            message=message,
            output_path=output_path,
        )

    def export_ts(self, request: JobRequest) -> JobResult:
        """
        Export a TS CSV through the existing scanner export dialog actions.
        """

        output_path = build_output_path(
            output_dir=self.output_dir,
            source=SourceKind.TS,
            when=request.requested_at,
            target_filename=request.target_filename,
        )

        if self.dry_run:
            output_path.parent.mkdir(parents=True, exist_ok=True)

            output_path.write_text(
                "Symbol,Source,Note\n"
                "DRYRUN,TS,Generated by ToSScanActionExecutor dry run\n",
                encoding="utf-8",
            )

            message = f"DRY RUN: wrote stub TS CSV to {output_path}"
            self._log_info(message)

            return JobResult(
                request=request,
                ok=True,
                message=message,
                output_path=output_path,
            )

        try:
            self._export_ts_with_existing_controller(output_path)
            if not self._wait_for_output_file(output_path, timeout_s=5.0):
                raise RuntimeError(f"TS export file did not appear: {output_path}")

        except Exception as exc:
            message = f"TS export failed: {exc}"
            self._log_error(message)

            return JobResult(
                request=request,
                ok=False,
                message=message,
                output_path=output_path,
                error=str(exc),
            )

        message = f"Exported TS CSV to {output_path}"
        self._log_info(message)

        return JobResult(
            request=request,
            ok=True,
            message=message,
            output_path=output_path,
        )


    def _export_wl_with_existing_controller(self, output_path: Path) -> None:
        """
        Bridge v2 EXPORT_WL into the existing ToS watchlist export actions.

        Conservative sequence:
            open_watchlist_export()
            normalize_watchlist_export_dialog()
            enter_watchlist_filename_then_export_directory(filename, target_dir)
            confirm_watchlist_save()

        We set filename first, then directory, because changing the directory
        field can move/affect the filename field in the export dialog.
        """

        if self.action_controller is None:
            raise RuntimeError("No action_controller was provided.")

        controller = self.action_controller

        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        filename = output_path.name
        target_dir = output_path.parent

        self._log_info(f"WL export target filename: {filename}")
        self._log_info(f"WL export target directory: {target_dir}")

        controller.open_watchlist_export()
        controller.normalize_watchlist_export_dialog()
        controller.enter_watchlist_filename_then_export_directory(
            filename,
            target_dir,
        )
        controller.confirm_watchlist_save()


    def _export_ts_with_existing_controller(self, output_path: Path) -> None:
        """
        Bridge v2 EXPORT_TS into the existing ToS scanner export actions.
        """

        if self.action_controller is None:
            raise RuntimeError("No action_controller was provided.")

        controller = self.action_controller

        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        filename = output_path.name
        target_dir = output_path.parent

        self._log_info(f"TS export target filename: {filename}")
        self._log_info(f"TS export target directory: {target_dir}")

        controller.export_csv_file()
        controller.normalize_scan_export_dialog()
        controller.enter_filename(
            filename,
            target_dir,
        )
        controller.confirm_save()


    def _log_info(self, message: str) -> None:
        if self.logger is not None:
            self.logger.info(message)

    def _log_error(self, message: str) -> None:
        if self.logger is not None:
            self.logger.error(message)

